### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by vinitkumar** [comment]
@crydotsnake Tests are  failing,  please  take a look. https://github.com/crydotsnake/djangocms-style/runs/2368782046?check_suite_focus=true

**Comment by marksweb** [comment]
> @crydotsnake Tests are  failing,  please  take a look. https://github.com/crydotsnake/djangocms-style/runs/2368782046?check_suite_focus=true

Yeah requirements files are missing. I can't see actions from the github mobile app, but it told me alll as ok to merge. Clearly its not. 🤦‍♂️

**Review by marksweb — CHANGES_REQUESTED** [review]
Requirements files missing

**Comment by crydotsnake** [comment]
https://github.com/django-cms/djangocms-history/actions Here also i believe..

I think I was too fast..

**Comment by marksweb** [comment]
> https://github.com/django-cms/djangocms-history/actions Here also i believe..
> 
> I think I was too fast..

Me to! Trying to quickly review from my phone 🤦‍♂️

**Comment by crydotsnake** [comment]
@marksweb Thats interesting.. now i cant see the GitHub Action checks anymore in here. But i added the requirement files.

**Comment by marksweb** [comment]
> @marksweb Thats interesting.. now i cant see the GitHub Action checks anymore in here. But i added the requirement files.

They're running on your branch

https://github.com/crydotsnake/djangocms-style/actions

**Comment by crydotsnake** [comment]
But before i saw the checks also here in the PR

**Review by marksweb — APPROVED** [review]

**Comment by crydotsnake** [comment]
Okay. Glad the checks seems to be okay ! 😊

**Comment by marksweb** [comment]
> Okay. Glad the checks seems to be okay ! 😊 . Because i was not sure 🙈 

I've looked at so many of these PRs now that I can't remember if they checks run before the merge. I'm assuming not, because they're not here, but your branch has them running and passing.

**Review by vinitkumar — APPROVED** [review]

**Pull request merged**
